.TH BATINFO 1 "October 2024" "Version 0.1" "BATINFO Manual"
.SH NAME
batinfo \- A simple battery information tool, useful in tty & minimalistic environments.
.SH SYNOPSIS
.B batinfo
[\-p | \-s | \-a | \-t | \-r | \-x | \-v | \-h]
.SH DESCRIPTION
.B batinfo
is a simple command-line tool that retrieves battery information from your Linux system.

.SH OPTIONS
.TP
.BR \-p ,\ \-\-capacity
Show battery capacity.
.TP
.BR \-s ,\ \-\-status
Show battery status.
.TP
.BR \-a ,\ \-\-ac
Show if power source is AC or Battery.
.TP
.BR \-t ,\ \-\-time
Show estimated time remaining based on the current discharge rate.
.TP
.BR \-r ,\ \-\-rate
Show the current charge or discharge rate in watts.
.TP
.BR \-x ,\ \-\-all
Show all available battery information.
.TP
.BR \-v ,\ \-\-version
Display version information.
.TP
.BR \-h ,\ \-\-help
Show help message and available options.

.SH LICENSE
BSD License

.SH AUTHOR
Abdulrahman Nader  <abdulrahmanxso25@outlook.com>
.BATINFO
October 2024
